title: "0x4447"
name    : David Gatti
email   : david@0x4447.com
description: >- # this means to ignore newlines until "baseurl:"
source: ./_src
url: "" # https://example.com/
google_analytics: UA-TODO
permalink: pretty
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

defaults:
  -
    scope:
      path: 'assets/libs/**'
    values:
      sitemap: false
  -
    scope:
      path: 'assets/js/**'
    values:
      sitemap: false
